# Generated by Django 5.2.5 on 2025-08-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='genre',
            new_name='genres',
        ),
    ]
